name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CRAFT_APP_ID: craftmcp
      CRAFT_ENVIRONMENT: dev
      CRAFT_SECURITY_KEY: lolz
      CRAFT_DB_DRIVER: mysql
      CRAFT_DB_SERVER: 127.0.0.1
      CRAFT_DB_PORT: 3306
      CRAFT_DB_DATABASE: craftmcp
      CRAFT_DB_USER: root
      CRAFT_DB_PASSWORD: root
      CRAFT_DB_TABLE_PREFIX: craft_
      CRAFT_DEV_MODE: true
      PRIMARY_SITE_URL: http://localhost:8080

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: craftmcp
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: |
            composer.lock
            vendor
          key: ${{ runner.os }}-craft-${{ matrix.version.constraint }}-vendor-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: |
          composer require "craftcms/cms:~5.8.8" --prefer-dist --no-progress

      - name: Copy config files
        run: |
          mkdir -p ./config/
          cp -r ./stubs/project/ ./config/project/

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse src

      - name: Run test suite
        run: ./vendor/bin/pest
        if: always()
